//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public decimal Count { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
